# Generated by Django 3.2.6 on 2022-05-20 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='title',
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=70, verbose_name='Genre name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2022, 5, 20, 5, 45, 43, 487414, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kitobni nomi')),
                ('author', models.CharField(max_length=50, verbose_name='kitob aftori')),
                ('slug', models.SlugField(max_length=100)),
                ('book_img', models.ImageField(upload_to='movie_posters/%Y/%m', verbose_name='Rasmi')),
                ('city', models.CharField(max_length=50, unique=True, verbose_name='SHahri')),
                ('time', models.CharField(default='00:00', max_length=50)),
                ('genre', models.ManyToManyField(to='movie.Genre')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
