# Generated by Django 3.2.6 on 2022-05-20 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20220520_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default=datetime.datetime(2022, 5, 20, 5, 54, 28, 832991, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
